// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izjabzimdscckeixkyle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6amFiemltZHNjY2tlaXhreWxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzOTk3NDMsImV4cCI6MjA1OTk3NTc0M30._srkm-WxkjpUqOWkCa5PLQJVhO271loM_yDdTden7gQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);